### ISSUE TITLE
version: uaclient version cannot use git describe in git-ubuntu packaging branches

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1058]
During reviews up git-ubuntu uploads,  `git describe --match=[0-9]*` on git-ubuntu pkg branches does not resolve to an upstream annotated tag of the form XX.Y resulting in a CalledProcessError that traces when running tox.

```

fatal: No names found, cannot describe anything.
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    version=_get_version(),
  File "setup.py", line 16, in _get_version
    parts = version.get_version().split("-")
  File "/home/bryce/ubuntu/UbuntuAdvantageTools/ubuntu-advantage-tools/uaclient/version.py", line 22, in get_version
    return check_output(cmd, universal_newlines=True).strip()
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'describe', '--abbrev=8', '--match=[0-9]*', '--long']' returned non-zero exit status 128.
```

**Comment by blackboxsw** [comment]
Resolved by commit https://github.com/canonical/ubuntu-advantage-client/commit/64934fa1ab31a0e704864dd8068c61f5dd8e09f2
