### ISSUE TITLE
Flake8 error for 24.1 release

### ISSUE THREAD

**Issue by lucasmoura** [canonical/ubuntu-advantage-client#1062]
When running the `tox -e flake8-xenial` test, the following error is raised:

```
GLOB sdist-make: /home/lucasmoura/ubuntu-advantage-tools/setup.py
flake8-xenial create: /home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial
flake8-xenial installdeps: -rrequirements.txt, -rtest-requirements.txt, -ctools/constraints-xenial.txt
flake8-xenial inst: /home/lucasmoura/ubuntu-advantage-tools/.tox/.tmp/package/1/ubuntu-advantage-tools-24.1.zip
flake8-xenial installed: behave==1.2.6,coverage==5.1,flake8==2.5.4,mccabe==0.4.0,mock==4.0.2,parse==1.15.0,parse-type==0.5.2,pep8==1.7.0,py==1.4.31,pycodestyle==2.6.0,pyflakes==1.0.0,PyHamcrest==2.0.2,pytest==2.8.7,pytest-cov==2.2.1,PyYAML==3.11,six==1.15.0,ubuntu-advantage-tools @ file:///home/lucasmoura/ubuntu-advantage-tools/.tox/.tmp/package/1/ubuntu-advantage-tools-24.1.zip
flake8-xenial run-test-pre: PYTHONHASHSEED='3520802523'
flake8-xenial run-test: commands[0] | flake8 uaclient setup.py
/home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/lib/python3.8/site-packages/pep8.py:109: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
Traceback (most recent call last):
  File "/home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/lib/python3.8/site-packages/flake8/main.py", line 33, in main
    report = flake8_style.check_files()
  File "/home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/lib/python3.8/site-packages/flake8/engine.py", line 181, in check_files
    return self._retry_serial(self._styleguide.check_files, paths=paths)
  File "/home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/lib/python3.8/site-packages/flake8/engine.py", line 172, in _retry_serial
    return func(*args, **kwargs)
  File "/home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/lib/python3.8/site-packages/pep8.py", line 1840, in check_files
    self.input_dir(path)
  File "/home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/lib/python3.8/site-packages/pep8.py", line 1876, in input_dir
    runner(os.path.join(root, filename))
  File "/home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/lib/python3.8/site-packages/flake8/engine.py", line 126, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/lib/python3.8/site-packages/pep8.py", line 1574, in check_all
    self.check_ast()
  File "/home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/lib/python3.8/site-packages/pep8.py", line 1520, in check_ast
    checker = cls(tree, self.filename)
  File "/home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/lib/python3.8/site-packages/flake8/_pyflakes.py", line 61, in __init__
    super(FlakesChecker, self).__init__(tree, filename,
  File "/home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/lib/python3.8/site-packages/pyflakes/checker.py", line 294, in __init__
    self.handleChildren(tree)
  File "/home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/lib/python3.8/site-packages/pyflakes/checker.py", line 567, in handleChildren
    self.handleNode(node, tree)
  File "/home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/lib/python3.8/site-packages/pyflakes/checker.py", line 609, in handleNode
    handler(node)
  File "/home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/lib/python3.8/site-packages/pyflakes/checker.py", line 567, in handleChildren
    self.handleNode(node, tree)
  File "/home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/lib/python3.8/site-packages/pyflakes/checker.py", line 608, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "/home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/lib/python3.8/site-packages/pyflakes/checker.py", line 462, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'
ERROR: InvocationError for command /home/lucasmoura/ubuntu-advantage-tools/.tox/flake8-xenial/bin/flake8 uaclient setup.py (exited with code 1)
```

This is also happening for `flake8-bionic`

**Comment by orndorffgrant** [comment]
We are passing flake8 now :)
