### ISSUE TITLE
auto-attach fails when trying to use Ubuntu Pro images with Juju 2.8

### ISSUE THREAD

**Issue by cmars** [canonical/ubuntu-advantage-client#1136]
See Juju bug https://bugs.launchpad.net/juju/+bug/1889458 for background.. but basically, if I configure Juju to use Ubuntu Pro AMIs for bionic in us-east-1 and manage to get Juju to create the instance (you might need to use a region where you've launched Pro before), ua auto-attach seems to be failing.

This only seems to happen when Juju provisions the machine and I can't figure out why. If I launch Ubuntu Pro from the EC2 dashboard it works fine.

Steps to reproduce:
0. Maybe launch a 18.04 Pro instance in us-east-1 if you've never done it
1. `juju bootstrap aws/us-east-1`. You'll need to add AWS cloud credentials to Juju first.
2. `juju metadata add-image --series bionic ami-09109b16d2d9d5779` to tell Juju to use Pro bionic instead of LTS
3. `juju deploy ubuntu`
4. `juju ssh ubuntu/0` after it comes up. Might need to `watch juju status` to monitor this.

This is what I get in /var/log/ubuntu-advantage.log when trying to auto-attach on such an instance:
```
2020-07-29 21:47:53,331 - util.py:(373) [DEBUG]: Reading file: /sys/hypervisor/uuid
2020-07-29 21:47:53,331 - util.py:(373) [DEBUG]: Reading file: /sys/class/dmi/id/product_uuid
2020-07-29 21:47:53,332 - util.py:(373) [DEBUG]: Reading file: /sys/class/dmi/id/product_serial
2020-07-29 21:47:53,332 - util.py:(373) [DEBUG]: Reading file: /etc/os-release
2020-07-29 21:47:54,916 - cli.py:(637) [ERROR]: Unhandled exception, please file a bug
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 614, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 660, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 52, in new_f
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 425, in action_auto_attach
    token = _get_contract_token_from_cloud_identity(cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 396, in _get_contract_token_from_cloud_identity
    current_iid = identity.get_instance_id()
  File "/usr/lib/python3/dist-packages/uaclient/clouds/identity.py", line 31, in get_instance_id
    out, _err = util.subp(["cloud-init", "query", "instance_id"])
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 518, in subp
    out, err = _subp(args, rcs, capture, timeout)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 478, in _subp
    stderr=err.decode("utf-8"),
uaclient.util.ProcessExecutionError: Failed running command 'cloud-init query instance_id' [exit(1)]. Message: Traceback (most recent call last):
  File "/usr/bin/cloud-init", line 11, in <module>
    load_entry_point('cloud-init==20.2', 'console_scripts', 'cloud-init')()
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 893, in main
    get_uptime=True, func=functor, args=(name, args))
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2620, in log_time
    ret = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/query.py", line 123, in handle_args
    instance_data['userdata'] = util.load_file(user_data_fn)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 1432, in load_file
    return decode_binary(contents)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 132, in decode_binary
    return blob.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by blackboxsw** [comment]
Triaged to general juju deploy ubuntu error with 'cloud-init query' and compressed user-data 
https://bugs.launchpad.net/cloud-init/+bug/1889938

PR up for cloud-init to fix this
https://github.com/canonical/cloud-init/pull/516

**Comment by blackboxsw** [comment]
While we await SRU of the cloud-init fix here is a workaround for juju in ubuntu-advantage-client to proceed with testing:

```
# Create a juju cloudinit-userdata.yaml file which uses non-root to call cloud-init query instance_id
cat > non-root-cloud-init-query.yaml <<EOF

cloudinit-userdata: |
  write_files:
  - path: /usr/lib/python3/dist-packages/uaclient/clouds/identity.py
    encoding: b64
    permissions: '0644'
    owner: root:root
    content: |
     aW1wb3J0IGpzb24KaW1wb3J0IGxvZ2dpbmcKaW1wb3J0IG11bHRpcHJvY2Vzc2luZwppbXBvcnQg
     b3MKCmZyb20gdWFjbGllbnQgaW1wb3J0IGV4Y2VwdGlvbnMKZnJvbSB1YWNsaWVudCBpbXBvcnQg
     Y2xvdWRzCmZyb20gdWFjbGllbnQgaW1wb3J0IHN0YXR1cwpmcm9tIHVhY2xpZW50IGltcG9ydCB1
     dGlsCgp0cnk6CiAgICBmcm9tIHR5cGluZyBpbXBvcnQgT3B0aW9uYWwgICMgbm9xYTogRjQwMQpl
     eGNlcHQgSW1wb3J0RXJyb3I6CiAgICAjIHR5cGluZyBpc24ndCBhdmFpbGFibGUgb24gdHJ1c3R5
     LCBzbyBpZ25vcmUgaXRzIGFic2VuY2UKICAgIHBhc3MKCiMgTmVlZGVkIGZvciBUcnVzdHktb25s
     eQpDTE9VRElOSVRfUkVTVUxUX0ZJTEUgPSAiL3Zhci9saWIvY2xvdWQvZGF0YS9yZXN1bHQuanNv
     biIKQ0xPVURJTklUX0lOU1RBTkNFX0lEX0ZJTEUgPSAiL3Zhci9saWIvY2xvdWQvZGF0YS9pbnN0
     YW5jZS1pZCIKCgojIE1hcHBpbmcgb2YgZGF0YXNvdXJjZSBuYW1lcyB0byBjbG91ZC1pZCByZXNw
     b25zZXMuIFRydXN0eSBjb21wYXQgd2l0aCBYZW5pYWwrCkRBVEFTT1VSQ0VfVE9fQ0xPVURfSUQg
     PSB7ImF6dXJlbmV0IjogImF6dXJlIiwgImVjMiI6ICJhd3MifQoKCmRlZiBxdWVyeV9hc19ub25f
     cm9vdChxOiBtdWx0aXByb2Nlc3NpbmcuUXVldWUpIC0+IE5vbmU6CiAgICAiIiJEZW1vdGUgcm9v
     dCB1c2VyIHRvIGNhbGwgY2xvdWQtaW5pdCBxdWVyeS4KCiAgICBQdXQgdGhlIHJlc3BvbnNlIG9m
     IGNsb3VkLWluaXQgcXVlcnkgb24gdGhlIHByb3ZpZGVkIFF1ZXVlLgoKICAgIFVzZSBkZW1vdGlv
     biBhdm9pZHMgZXJyb3Igb24gY29tcHJlc3NlZCB1c2VyLWRhdGEgb24gc29tZSBwbGF0Zm9ybXMu
     CiAgICBUT0RPKENhbiBydW4gYXMgcm9vdCBvbmNlICBMUDogIzE4ODk5MzggU1JVcyB0byBYZW5p
     YWwpCiAgICAiIiIKICAgIGlmIG9zLmdldHVpZCgpID09IDA6CiAgICAgICAgb3Muc2V0Z2lkKDEw
     MDApCiAgICAgICAgb3Muc2V0dWlkKDEwMDApCiAgICBvdXQsIF9lcnIgPSB1dGlsLnN1YnAoWyJj
     bG91ZC1pbml0IiwgInF1ZXJ5IiwgImluc3RhbmNlX2lkIl0pCiAgICBxLnB1dChvdXQuc3RyaXAo
     KSkKCgpkZWYgZ2V0X2luc3RhbmNlX2lkX2Zyb21fY2xvdWRpbml0X3F1ZXJ5KCk6CiAgICAiIiJS
     ZXR1cm4gY3VycmVudCBpbnN0YW5jZV9pZCBmcm9tIGNsb3VkIG1ldGFkYXRhIiIiCiAgICBjdHgg
     PSBtdWx0aXByb2Nlc3NpbmcuZ2V0X2NvbnRleHQoInNwYXduIikKICAgIHEgPSBjdHguUXVldWUo
     KQogICAgcCA9IGN0eC5Qcm9jZXNzKHRhcmdldD1xdWVyeV9hc19ub25fcm9vdCwgYXJncz0ocSwp
     KQogICAgcC5zdGFydCgpCiAgICBpbnN0YW5jZV9pZCA9IHEuZ2V0KCkKICAgIHAuam9pbigpCiAg
     ICByZXR1cm4gaW5zdGFuY2VfaWQKCgpkZWYgZ2V0X2luc3RhbmNlX2lkKAogICAgX2lpZF9maWxl
     OiBzdHIgPSBDTE9VRElOSVRfSU5TVEFOQ0VfSURfRklMRQopIC0+ICJPcHRpb25hbFtzdHJdIjoK
     ICAgICIiIlF1ZXJ5IGNsb3VkIGluc3RhbmNlLWlkIGZyb20gY21kbGluZSBvciBDTE9VRElOSVRf
     SU5TVEFOQ0VfSURfRklMRSIiIgogICAgaWYgInRydXN0eSIgIT0gdXRpbC5nZXRfcGxhdGZvcm1f
     aW5mbygpWyJzZXJpZXMiXToKICAgICAgICAjIFByZXNlbnQgaW4gY2xvdWQtaW5pdCBvbiA+PSBY
     ZW5pYWwKICAgICAgICByZXR1cm4gZ2V0X2luc3RhbmNlX2lkX2Zyb21fY2xvdWRpbml0X3F1ZXJ5
     KCkKICAgIGlmIG9zLnBhdGguZXhpc3RzKF9paWRfZmlsZSk6CiAgICAgICAgcmV0dXJuIHV0aWwu
     bG9hZF9maWxlKF9paWRfZmlsZSkKICAgIGxvZ2dpbmcud2FybmluZygKICAgICAgICAiVW5hYmxl
     IHRvIGRldGVybWluZSBjdXJyZW50IGluc3RhbmNlLWlkIGZyb20gJXMiLCBfaWlkX2ZpbGUKICAg
     ICkKICAgIHJldHVybiBOb25lCgoKZGVmIGdldF9jbG91ZF90eXBlX2Zyb21fcmVzdWx0X2ZpbGUo
     CiAgICByZXN1bHRfZmlsZTogc3RyID0gQ0xPVURJTklUX1JFU1VMVF9GSUxFCikgLT4gc3RyOgog
     ICAgcmVzdWx0ID0ganNvbi5sb2Fkcyh1dGlsLmxvYWRfZmlsZShyZXN1bHRfZmlsZSkpCiAgICBk
     c25hbWUgPSByZXN1bHRbInYxIl1bImRhdGFzb3VyY2UiXS5zcGxpdCgpWzBdLmxvd2VyKCkKICAg
     IGRzbmFtZSA9IGRzbmFtZS5yZXBsYWNlKCJkYXRhc291cmNlIiwgIiIpCiAgICByZXR1cm4gREFU
     QVNPVVJDRV9UT19DTE9VRF9JRC5nZXQoZHNuYW1lLCBkc25hbWUpCgoKZGVmIGdldF9jbG91ZF90
     eXBlKCkgLT4gIk9wdGlvbmFsW3N0cl0iOgogICAgaWYgdXRpbC53aGljaCgiY2xvdWQtaWQiKToK
     ICAgICAgICAjIFByZXNlbnQgaW4gY2xvdWQtaW5pdCBvbiA+PSBYZW5pYWwKICAgICAgICBvdXQs
     IF9lcnIgPSB1dGlsLnN1YnAoWyJjbG91ZC1pZCJdKQogICAgICAgIHJldHVybiBvdXQuc3RyaXAo
     KQogICAgdHJ5OgogICAgICAgIHJldHVybiBnZXRfY2xvdWRfdHlwZV9mcm9tX3Jlc3VsdF9maWxl
     KCkKICAgIGV4Y2VwdCBGaWxlTm90Rm91bmRFcnJvcjoKICAgICAgICBwYXNzCiAgICByZXR1cm4g
     Tm9uZQoKCmRlZiBjbG91ZF9pbnN0YW5jZV9mYWN0b3J5KCkgLT4gY2xvdWRzLkF1dG9BdHRhY2hD
     bG91ZEluc3RhbmNlOgogICAgZnJvbSB1YWNsaWVudC5jbG91ZHMgaW1wb3J0IGF3cwogICAgZnJv
     bSB1YWNsaWVudC5jbG91ZHMgaW1wb3J0IGF6dXJlCgogICAgY2xvdWRfaW5zdGFuY2VfbWFwID0g
     ewogICAgICAgICJhd3MiOiBhd3MuVUFBdXRvQXR0YWNoQVdTSW5zdGFuY2UsCiAgICAgICAgImF3
     cy1jaGluYSI6IGF3cy5VQUF1dG9BdHRhY2hBV1NJbnN0YW5jZSwKICAgICAgICAiYXdzLWdvdiI6
     IGF3cy5VQUF1dG9BdHRhY2hBV1NJbnN0YW5jZSwKICAgICAgICAiYXp1cmUiOiBhenVyZS5VQUF1
     dG9BdHRhY2hBenVyZUluc3RhbmNlLAogICAgfQoKICAgIGNsb3VkX3R5cGUgPSBnZXRfY2xvdWRf
     dHlwZSgpCiAgICBpZiBub3QgY2xvdWRfdHlwZToKICAgICAgICByYWlzZSBleGNlcHRpb25zLlVz
     ZXJGYWNpbmdFcnJvcigKICAgICAgICAgICAgc3RhdHVzLk1FU1NBR0VfVU5BQkxFX1RPX0RFVEVS
     TUlORV9DTE9VRF9UWVBFCiAgICAgICAgKQogICAgY2xzID0gY2xvdWRfaW5zdGFuY2VfbWFwLmdl
     dChjbG91ZF90eXBlKQogICAgaWYgbm90IGNsczoKICAgICAgICByYWlzZSBleGNlcHRpb25zLk5v
     bkF1dG9BdHRhY2hJbWFnZUVycm9yKAogICAgICAgICAgICBzdGF0dXMuTUVTU0FHRV9VTlNVUFBP
     UlRFRF9BVVRPX0FUVEFDSF9DTE9VRF9UWVBFLmZvcm1hdCgKICAgICAgICAgICAgICAgIGNsb3Vk
     X3R5cGU9Y2xvdWRfdHlwZQogICAgICAgICAgICApCiAgICAgICAgKQogICAgaW5zdGFuY2UgPSBj
     bHMoKQogICAgaWYgbm90IGluc3RhbmNlLmlzX3ZpYWJsZToKICAgICAgICByYWlzZSBleGNlcHRp
     b25zLlVzZXJGYWNpbmdFcnJvcigKICAgICAgICAgICAgc3RhdHVzLk1FU1NBR0VfVU5TVVBQT1JU
     RURfQVVUT19BVFRBQ0gKICAgICAgICApCiAgICByZXR1cm4gaW5zdGFuY2UK
EOF


# Setup juju model to use this cloud-config

1.    juju bootstrap aws/us-east-1. You'll need to add AWS cloud credentials to Juju first.
2.    juju metadata add-image --series bionic ami-0e11aa8c6a6d58146 to tell Juju to use Pro bionic instead of LTS
3.    juju model-config non-root-cloud-init-query.yaml 
4.    juju deploy ubuntu
5.    juju ssh ubuntu/0 after it comes up. Might need to watch juju status to monitor this.

**Comment by blackboxsw** [comment]
so  cloud-init version 20.3 fixes this issue.it will be released to groovy this week, and should be SRU'd by next week to xenial

**Comment by blackboxsw** [comment]
cloud-init version 20.3-2 is live in Xenial Bionic focal and Groovy. So this is resolved for ua-tools

**Comment by cmars** [comment]
@morphis FYI

**Comment by morphis** [comment]
Thanks @cmars ! @blackboxsw will the non-root-cloud-init-query.yaml workaround be necessary going forward or should that be fixed in the latest cloud images?
