### ISSUE TITLE
ci: intermittent error on focal

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1415]
Unreproducible when locally running
```bash
  Scenario: Attached enable of vm-based services in a focal lxd vm                        # features/attached_enable.feature:221
    Given a `focal` machine with ubuntu-advantage-tools installed                         # features/steps/steps.py:27
      Traceback (most recent call last):
        File "/jenkins/servers/private/workspace/_ubuntu-advantage-client_PR-1412/.tox/behave-vm-20.04/lib/python3.6/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/jenkins/servers/private/workspace/_ubuntu-advantage-client_PR-1412/.tox/behave-vm-20.04/lib/python3.6/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/steps.py", line 70, in given_a_machine
          image_name=context.series_image_name[series],
        File "/jenkins/servers/private/workspace/_ubuntu-advantage-client_PR-1412/features/cloud.py", line 140, in launch
          user_data=user_data,
        File "/jenkins/servers/private/workspace/_ubuntu-advantage-client_PR-1412/features/cloud.py", line 669, in _create_instance
          name=instance_name, image_id=image_name, user_data=user_data
        File "/jenkins/servers/private/workspace/_ubuntu-advantage-client_PR-1412/.tox/behave-vm-20.04/lib/python3.6/site-packages/pycloudlib/lxd/cloud.py", line 280, in launch
          execute_via_ssh=execute_via_ssh,
        File "/jenkins/servers/private/workspace/_ubuntu-advantage-client_PR-1412/.tox/behave-vm-20.04/lib/python3.6/site-packages/pycloudlib/lxd/cloud.py", line 232, in init
          result = subp(cmd)
        File "/jenkins/servers/private/workspace/_ubuntu-advantage-client_PR-1412/.tox/behave-vm-20.04/lib/python3.6/site-packages/pycloudlib/util.py", line 201, in subp
          raise RuntimeError(errmsg)
      RuntimeError: Failure (rc=1): Error: websocket: close 1006 (abnormal closure): unexpected EOF
```

**Comment by lucasmoura** [comment]
This error is happening on all series, unfortunately

**Comment by mitechie** [comment]
It's not clear to me in the traceback since it is in "create_instance" but
fyi all canonical tokens seemed to be lost and I had to get new ones set up
on my account. I'm not sure if this credential issue might have impacted
testing and if we need to update tokens used in testing.

**Comment by lucasmoura** [comment]
Not, it should not be related to that. This are LXD test, which don't use any credentials. For those tests, we generate a SSH key to be used in the LXD instance and issue all commands using it. However, I still don't know what could be causing this issue.

@paride yesterday mentioned that this issue may be related to paramiko banner_timeout:
https://docs.paramiko.org/en/stable/api/client.html

But I have not fully investigated this issue to confirm or deny that
