### ISSUE TITLE
logs: don't log tracebacks in non-error conditions when a message would suffice

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1586]
When already attached: ua attach should not log a traceback, but leave a message "Unable to re-attach when a machine is already attached."
Tracebacks in logs in general scare people. Reserve that for when there is an unhandled error condition

**Comment by orndorffgrant** [comment]
Another case where this happens is when the user tries to enable a service that doesn't exist (or that is beta without the --beta flag)

Example logs:
```
2021-04-28 03:17:48,631 - cli.py:(1026) [ERROR]: Cannot enable unknown service 'esm-apps'.
Try esm-infra, fips, fips-updates, livepatch.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 1004, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 1062, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 147, in new_f
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 170, in new_f
    return f(args, cfg, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 130, in new_f
    retval = f(args, cfg, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 604, in action_enable
    raise exceptions.UserFacingError(
uaclient.exceptions.UserFacingError: Cannot enable unknown service 'esm-apps'.
Try esm-infra, fips, fips-updates, livepatch.
```
