### ISSUE TITLE
Error activating CIS tool while launching AWS Pro instance with IMDSv2/ IMDSv1

### ISSUE THREAD

**Issue by ariannalozano** [canonical/ubuntu-advantage-client#1608]
Ran into a problem on this command while trying to gain access to the CIS beta tool for Ubuntu Pro:

sudo ua enable cis --beta

I was running this on aws us-west-2 from an ubuntu 18 pro instance and I get this output: 

To use 'cis' you need an Ubuntu Advantage subscription
Personal and community subscriptions are available at no charge
See https://ubuntu.com/advantage

I was on 26.3~18.04.1, with those commands I got upgraded to 27.0~18.04.1

If i run ua status --all I get 

SERVICE       AVAILABLE  DESCRIPTION
cc-eal        no         Common Criteria EAL2 Provisioning Packages
cis           yes        Center for Internet Security Audit Tools
esm-apps      yes        UA Apps: Extended Security Maintenance (ESM)
esm-infra     yes        UA Infra: Extended Security Maintenance (ESM)
fips          yes        NIST-certified FIPS modules
fips-updates  yes        Uncertified security updates to FIPS modules
livepatch     yes        Canonical Livepatch service

This machine is not attached to a UA subscription.
See https://ubuntu.com/advantage

But i can still not active cis: 

 sudo ua enable cis --beta
To use 'cis' you need an Ubuntu Advantage subscription
Personal and community subscriptions are available at no charge
See https://ubuntu.com/advantage

I can also confirm that I was trying this on an Ubuntu Pro image.

Tried running "sudo ua auto-attach", here is the output: 
It gives an error (see attached), here are the logs: 

2021-05-03 10:15:02,308 - cli.py:(1060) [DEBUG]: Executed with sys.argv: ['/usr/bin/ua', 'auto-attach']
2021-05-03 10:15:02,308 - util.py:(414) [DEBUG]: Reading file: /var/lib/ubuntu-advantage/notices.json
2021-05-03 10:15:02,309 - config.py:(357) [DEBUG]: File does not exist: /var/lib/ubuntu-advantage/notices.json
2021-05-03 10:15:02,309 - util.py:(646) [DEBUG]: Writing file: /var/lib/ubuntu-advantage/notices.json
2021-05-03 10:15:02,309 - util.py:(646) [DEBUG]: Writing file: /var/lib/ubuntu-advantage/private/lock
2021-05-03 10:15:02,309 - util.py:(414) [DEBUG]: Reading file: /var/lib/ubuntu-advantage/notices.json
2021-05-03 10:15:02,310 - config.py:(672) [DEBUG]: Using UA client configuration file at /etc/ubuntu-advantage/uaclient.conf
2021-05-03 10:15:02,310 - util.py:(414) [DEBUG]: Reading file: /etc/ubuntu-advantage/uaclient.conf
2021-05-03 10:15:02,640 - util.py:(414) [DEBUG]: Reading file: /sys/hypervisor/uuid
2021-05-03 10:15:02,641 - util.py:(414) [DEBUG]: Reading file: /etc/os-release
2021-05-03 10:15:03,068 - util.py:(414) [DEBUG]: Reading file: /var/lib/ubuntu-advantage/private/machine-token.json
2021-05-03 10:15:03,069 - config.py:(357) [DEBUG]: File does not exist: /var/lib/ubuntu-advantage/private/machine-token.json
2021-05-03 10:15:03,070 - util.py:(495) [DEBUG]: URL [GET]: http://169.254.169.254/latest/dynamic/instance-identity/pkcs7, headers: {}, data: None
2021-05-03 10:15:03,074 - util.py:(254) [DEBUG]: HTTP Error 401: Unauthorized Retrying 3 more times.
2021-05-03 10:15:04,075 - util.py:(495) [DEBUG]: URL [GET]: http://169.254.169.254/latest/dynamic/instance-identity/pkcs7, headers: {}, data: None
2021-05-03 10:15:04,077 - util.py:(254) [DEBUG]: HTTP Error 401: Unauthorized Retrying 2 more times.
2021-05-03 10:15:06,080 - util.py:(495) [DEBUG]: URL [GET]: http://169.254.169.254/latest/dynamic/instance-identity/pkcs7, headers: {}, data: None
2021-05-03 10:15:06,081 - util.py:(254) [DEBUG]: HTTP Error 401: Unauthorized Retrying 1 more times.
2021-05-03 10:15:11,087 - util.py:(495) [DEBUG]: URL [GET]: http://169.254.169.254/latest/dynamic/instance-identity/pkcs7, headers: {}, data: None
2021-05-03 10:15:11,092 - cli.py:(1035) [ERROR]: Unhandled exception, please file a bug
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 1004, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 1062, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 147, in new_f
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 130, in new_f
    retval = f(args, cfg, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 755, in action_auto_attach
    token = _get_contract_token_from_cloud_identity(cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 730, in _get_contract_token_from_cloud_identity
    instance=instance
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 116, in request_auto_attach_contract_token
    data=instance.identity_doc,
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 252, in decorator
    raise e
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 249, in decorator
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/clouds/aws.py", line 26, in identity_doc
    response, _headers = util.readurl(IMDS_URL)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 499, in readurl
    resp = request.urlopen(req, timeout=timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
2021-05-03 10:15:11,094 - util.py:(414) [DEBUG]: Reading file: /var/lib/ubuntu-advantage/notices.json
2021-05-03 10:15:11,094 - util.py:(656) [DEBUG]: Removing file: /var/lib/ubuntu-advantage/notices.json

I actually think I know why this is. It's because I only activated IMDSv2 on the instance, since that's a security recommendation. I spun up an instance with IMDSv1 and it worked. 

All works now and have enabled metadata v1. Is this a bug? Would be nice to be able to disable v1. 

<img width="667" alt="Screenshot 2021-05-03 at 11 15 18" src="https://user-images.githubusercontent.com/79338110/116926574-2125fa00-ac20-11eb-8914-d7ec4f34dc3f.png">
<img width="967" alt="Screenshot 2021-04-30 at 19 01 58" src="https://user-images.githubusercontent.com/79338110/116926578-21be9080-ac20-11eb-8b77-65d165517028.png">

**Comment by mitechie** [comment]
Thanks for the bug report. We'll need to double check the imds v1 vs v2 and see what we can do to make sure this doesn't occur in the future.

**Comment by ariannalozano** [comment]
Thank you, Rick!

**Comment by orndorffgrant** [comment]
I looked into this a bit. We should probably follow the pattern of the AWS SDK as described [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html#imds-considerations). The short version is: Try IMDSv2 and if you don't get a response, fall back to IMDSv1.

In practice, this should look like attempting to get a token from `http://169.254.169.254/latest/api/token`, and if we get one, include it in our GET to `http://169.254.169.254/latest/dynamic/instance-identity/pkcs7` using the appropriate header.

As described by [the AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/verify-pkcs7.html):
IMDSv2
```
TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` \ 
&& curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/dynamic/instance-identity/pkcs7 >> pkcs7
```
IMDSv1
```
curl -s http://169.254.169.254/latest/dynamic/instance-identity/pkcs7 >> pkcs7
```

Since we aren't frequent consumers of IMDS (AFAIK), we should probably just re-request the token anytime we need to interact with IMDS (as opposed to setting a long TTL and caching it somewhere - extra complexity for not much gain). And then we can set the TTL to just a few seconds - just long enough to make the subsequent pkcs7 request. (see the `X-aws-ec2-metadata-token-ttl-second` header above).

There is also a note in the link at the top of this comment about setting a higher hop limit if you need to call IMDSv2 from within a container. I don't believe that we, as a client on the instance, have control over the hop limit, but it may be a good note to include in an error message if our IMDS calls fail (e.g. "If you've enabled IMDSv2 and are attaching in a container, you may need to set your IMDS hop limit to 2 as described here: LINK_TO_DOCS)

Last note: @blackboxsw I probably shouldn't own this issue because I still don't have company cloud creds and so I can't test any of the above.

**Comment by blackboxsw** [comment]
+1 @orndorffgrant I'll take this. Since I was involved in some of the IMDSv2 work on cloud-init https://github.com/canonical/cloud-init/commit/1f860e5ac7ebb5b809c72d8703a0b7cb3e84ccd0#diff-66c4d0c34e626a49273eda62819c3068f5501520b86f28e89e0f998cf4cf2027L208  I'll have a bit more context on implementation we can reuse over here.
