### ISSUE TITLE
Missing ca-certificates packages causes unclear/incorrect error message

### ISSUE THREAD

**Issue by alnvdl** [canonical/ubuntu-advantage-client#1618]
**Steps to reproduce**:
1. Starting from an Ubuntu that only has basic packages (e.g., the default `ubuntu` Docker image), run:
```sh
$ sudo ua status
```

**What happens**:
The following error is displayed:
```
Failed to connect to authentication server
Check your Internet connection and try again
```

**What is expected**:
A clearer error message (e.g., "failed to validate authentication server certificate" or even a hint to install `ca-certificates` (which fixes the problem).

This is the log for this error:
```
2021-05-07 16:04:57,499 - cli.py:(659) [DEBUG]: Executed with sys.argv: ['/usr/bin/ua', 'status']
2021-05-07 16:04:57,499 - util.py:(373) [DEBUG]: Reading file: /var/lib/ubuntu-advantage/private/machine-token.json
2021-05-07 16:04:57,499 - config.py:(177) [DEBUG]: File does not exist: /var/lib/ubuntu-advantage/private/machine-token.json
2021-05-07 16:04:57,500 - util.py:(373) [DEBUG]: Reading file: /etc/os-release
2021-05-07 16:04:57,510 - util.py:(412) [DEBUG]: URL [GET]: https://contracts.develop.canonical.com/v1/resources?architecture=amd64&series=focal&kernel=5.4.0-72-generic, headers: {'user-agent': 'UA-Client/20.3', 'accept': 'application/json', 'content-type': 'application/json'}, data: None
2021-05-07 16:04:57,679 - cli.py:(627) [ERROR]: Failed to connect to authentication server
Check your Internet connection and try again. Failed to access URL: https://contracts.develop.canonical.com/v1/resources?architecture=amd64&series=focal&kernel=5.4.0-72-generic. [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/serviceclient.py", line 51, in request_url
    response, headers = util.readurl(
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 419, in readurl
    resp = request.urlopen(req)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 614, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 660, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 540, in action_status
    output = ua_status.format_tabular(cfg.status())
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 312, in status
    response = self._unattached_status()
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 208, in _unattached_status
    resources = get_available_resources(self)
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 320, in get_available_resources
    resources = client.request_resources()
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 101, in request_resources
    resource_response, headers = self.request_url(
  File "/usr/lib/python3/dist-packages/uaclient/serviceclient.py", line 62, in request_url
    raise util.UrlError(
uaclient.util.UrlError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
```

**Comment by mitechie** [comment]
Thanks for this report. We'll see what we can do to detect the issue ahead of time and have a clear message to the user.
