### ISSUE TITLE
`KeyError: 'configStatus'` exception from postinst

### ISSUE THREAD

**Issue by iainlane** [canonical/ubuntu-advantage-client#1734]
I just did a `dist-upgrade` on my Impish system. I got this:

```
Unpacking ubuntu-advantage-tools (27.2~21.10.1) over (27.1~21.10.1.1) ...
...
Setting up ubuntu-advantage-tools (27.2~21.10.1) ...
Installing new version of config file /etc/ubuntu-advantage/uaclient.conf ...
Traceback (most recent call last):
  File "/usr/lib/ubuntu-advantage/patch_status_json.py", line 66, in <module>
    patch_status_json_schema_0_1(
  File "/usr/lib/ubuntu-advantage/patch_status_json.py", line 50, in patch_status_json_schema_0_1
    new_status["execution_status"] = new_status.pop("configStatus")
KeyError: 'configStatus'
```

Here is my `status.json` with IDs redacted:

```
{
  "_doc": "Content provided in json response is currently considered Experimental and may change",
  "attached": true,
  "expires": "n/a",
  "origin": "free",
  "services": [
    {
      "name": "cc-eal",
      "description": "Common Criteria EAL2 Provisioning Packages",
      "entitled": "yes",
      "status": "n/a",
      "statusDetails": "",
      "description_override": null
    },
    {
      "name": "cis-audit",
      "description": "Center for Internet Security Audit Tools",
      "entitled": "no",
      "status": "—",
      "statusDetails": "",
      "description_override": null
    },
    {
      "name": "esm-apps",
      "description": "UA Apps: Extended Security Maintenance",
      "entitled": "no",
      "status": "—",
      "statusDetails": "",
      "description_override": null
    },
    {
      "name": "esm-infra",
      "description": "UA Infra: Extended Security Maintenance",
      "entitled": "yes",
      "status": "enabled",
      "statusDetails": "ESM Infra is active",
      "description_override": null
    },
    {
      "name": "fips",
      "description": "NIST-certified FIPS modules",
      "entitled": "yes",
      "status": "n/a",
      "statusDetails": "",
      "description_override": null
    },
    {
      "name": "fips-updates",
      "description": "Uncertified security updates to FIPS modules",
      "entitled": "yes",
      "status": "n/a",
      "statusDetails": "",
      "description_override": null
    },
    {
      "name": "livepatch",
      "description": "Canonical Livepatch service",
      "entitled": "yes",
      "status": "enabled",
      "statusDetails": "",
      "description_override": null
    }
  ],
  "techSupportLevel": "n/a",
  "account": "xxxx",
  "account-id": "xxxx",
  "subscription": "xxxx",
  "subscription-id": "xxxx"
}
```

Seems like `configStatus` and `configStatusDetails` aren't there, so the code should handle this case.

**Comment by renanrodrigo** [comment]
Hello @iainlane, thanks for raising this issue.
I was able to reproduce, and the linked PR should fix it.
