### ISSUE TITLE
Failed running command 'cloud-id' in ubuntu 20.04

### ISSUE THREAD

**Issue by bsecker** [canonical/ubuntu-advantage-client#1775]
I'm trying to install FIPS mode on Ubuntu 20.04. Running this:
```
$ sudo ua enable fips
One moment, checking your subscription first
This will install the FIPS core packages.
Are you sure? (y/N) y
Unexpected error(s) occurred.
For more details, see the log: /var/log/ubuntu-advantage.log
To file a bug run: ubuntu-bug ubuntu-advantage-tools
```

And in `/var/log/ubuntu-advantage.log`:

```
2021-08-25 05:42:18,056 - config.py:(869) [DEBUG]: Using UA client configuration file at /etc/ubuntu-advantage/uaclient.conf
2021-08-25 05:42:18,057 - util.py:(419) [DEBUG]: Reading file: /etc/ubuntu-advantage/uaclient.conf
2021-08-25 05:42:18,267 - cli.py:(1297) [ERROR]: Unhandled exception, please file a bug
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 1256, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 1342, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 148, in new_f
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 171, in new_f
    return f(args, cfg, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 131, in new_f
    retval = f(args, cfg, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 791, in action_enable
    cfg.status()  # Update the status cache
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 681, in status
    response = self._attached_status()
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 654, in _attached_status
    self._attached_service_status(ent, inapplicable_resources)
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 589, in _attached_service_status
    ent_status, details = ent.user_facing_status()
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/base.py", line 589, in user_facing_status
    applicability, details = self.applicability_status()
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/base.py", line 379, in applicability_status
    for error_message, functor, expected_result in self.static_affordances:
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/fips.py", line 331, in static_affordances
    static_affordances = super().static_affordances
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/fips.py", line 176, in static_affordances
    cloud_id = get_cloud_type() or ""
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 940, in new_f
    return f()
  File "/usr/lib/python3/dist-packages/uaclient/clouds/identity.py", line 65, in get_cloud_type
    out, _err = util.subp(["cloud-id"])
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 638, in subp
    out, err = _subp(args, rcs, capture, timeout, env=env)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 591, in _subp
    raise ProcessExecutionError(
uaclient.util.ProcessExecutionError: Failed running command 'cloud-id' [exit(1)]. Message: ERROR: File not found '/run/cloud-init/instance-data.json'. Provide a path to instance data json file using --instance-data

2021-08-25 05:42:18,269 - util.py:(419) [DEBUG]: Reading file: /var/lib/ubuntu-advantage/notices.json
2021-08-25 05:42:18,269 - util.py:(686) [DEBUG]: Removing file: /var/lib/ubuntu-advantage/notices.json
```

Version:
```
$ ua version
27.2.2~20.04.1
```
The image I'm enabling FIPS mode on is a standard Ubuntu 20.04 image built with packer - I'm suspicious about the mentions of `cloud-init` as that was used in the packer build process, but then we disable cloud-init after the VM is built with `touch /etc/cloud/cloud-init.disabled`.

**Comment by bsecker** [comment]
It seems like this was fixed in https://github.com/canonical/ubuntu-advantage-client/issues/1541 so happy to close this issue. Is there any way to see which version that fix will make it into?

**Comment by mitechie** [comment]
It'll be cut in the next release 27.3 planned for the next week or so.
