### ISSUE TITLE
Unhandled exception on GCE when a VM doesn't have a service account

### ISSUE THREAD

**Issue by ikapelyukhin** [canonical/ubuntu-advantage-client#1832]
`ua` invocation:

```
# ua auto-attach
Unexpected error(s) occurred.
For more details, see the log: /var/log/ubuntu-advantage.log
To file a bug run: ubuntu-bug ubuntu-advantage-tools
```

Traceback in the log:

```
2021-10-04 17:00:41,330 - util.py:(259) [DEBUG]: HTTP Error 404: Not Found Retrying 1 more times.
2021-10-04 17:00:46,336 - util.py:(519) [DEBUG]: URL [GET]: http://metadata/computeMetadata/v1/instance/service-accounts/default/identity?audience=contracts.canonical.com&format=full&licenses=TRUE, headers: {'Metadata-Flavor': 'Google'}, data: None
2021-10-04 17:00:46,339 - cli.py:(1297) [ERROR]: Unhandled exception, please file a bug
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 1256, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 1342, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 148, in new_f
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 131, in new_f
    retval = f(args, cfg, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 973, in action_auto_attach
    token = _get_contract_token_from_cloud_identity(cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 947, in _get_contract_token_from_cloud_identity
    tokenResponse = contract_client.request_auto_attach_contract_token(
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 117, in request_auto_attach_contract_token
    data=instance.identity_doc,
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 257, in decorator
    raise e
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 254, in decorator
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/clouds/gcp.py", line 32, in identity_doc
    url_response, _headers = util.readurl(
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 529, in readurl
    resp = request.urlopen(req, timeout=timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

Raw metadata:

```
# curl -i -H 'Metadata-Flavor:Google' 'http://metadata/computeMetadata/v1/instance/service-accounts/default/identity?audience=contracts.canonical.com&format=full&licenses=TRUE'
HTTP/1.1 404 Not Found
Metadata-Flavor: Google
Date: Mon, 04 Oct 2021 17:04:51 GMT
Content-Type: text/html
Server: Metadata Server for VM
Content-Length: 94
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN

{"error":"invalid_request","error_description":"Service account not enabled on this instance"}
```

It would be nice to handle the exception and output a meaningful message, maybe with a link to [docs](https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances).

**Comment by blackboxsw** [comment]
Added JIRA card CS-591

**Comment by CalvoM** [comment]
Solved by the PR #2077
