### ISSUE TITLE
Misleading error message on GCE when a VM doesn't have a proper license

### ISSUE THREAD

**Issue by ikapelyukhin** [canonical/ubuntu-advantage-client#1833]
`ua` invocation:

```
# ua auto-attach
Failed to connect to authentication server
Check your Internet connection and try again.
```

Traceback from the log:

```
2021-10-04 17:56:46,892 - cli.py:(1281) [ERROR]: Failed to connect to authentication server
Check your Internet connection and try again. Failed to access URL: https://contracts.canonical.com/v1/clouds/gcp/token. Internal Server Error: [https://contracts.canonical.com/v1/clouds/gcp/token]missing product mapping for licenses [2211838267635035815]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/serviceclient.py", line 64, in request_url
    response, headers = util.readurl(
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 529, in readurl
    resp = request.urlopen(req, timeout=timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 1256, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 1342, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 148, in new_f
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 131, in new_f
    retval = f(args, cfg, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 973, in action_auto_attach
    token = _get_contract_token_from_cloud_identity(cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 955, in _get_contract_token_from_cloud_identity
    raise e
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 947, in _get_contract_token_from_cloud_identity
    tokenResponse = contract_client.request_auto_attach_contract_token(
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 113, in request_auto_attach_contract_token
    response, _headers = self.request_url(
  File "/usr/lib/python3/dist-packages/uaclient/serviceclient.py", line 81, in request_url
    raise self.api_error_cls(e, error_details)
uaclient.contract.ContractAPIError: Internal Server Error: [https://contracts.canonical.com/v1/clouds/gcp/token]missing product mapping for licenses [2211838267635035815]
```

Under certain circumstances it is possible for the instance to end up without a proper license, it would be nice to produce a more accurate error message.

**Comment by blackboxsw** [comment]
Created JIRA card
