### ISSUE TITLE
Unhandled exception during auto-attach on GCE

### ISSUE THREAD

**Issue by ikapelyukhin** [canonical/ubuntu-advantage-client#1936]
Filing a bug as the log suggests:

```
2022-01-14 17:27:33,439 - util.py:(572) [DEBUG]: URL [GET] response: http://metadata/computeMetadata/v1/instance/service-accounts/default/identity?audience=contracts.canonical.com&format=full&licenses=TRUE, headers: {'Connection': 'Close', 'Content-Length': '94', 'Content-Type': 'text/html', 'Date': 'Fri, 14 Jan 2022 17:27:33 GMT', 'Metadata-Flavor': 'Google', 'Server': 'Metadata Server for VM', 'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '0'}, data: <REDACTED>
2022-01-14 17:27:33,439 - util.py:(434) [DEBUG]: Reading file: /var/lib/ubuntu-advantage/notices.json
2022-01-14 17:27:33,440 - util.py:(726) [DEBUG]: Removing file: /var/lib/ubuntu-advantage/notices.json
2022-01-14 17:27:33,440 - cli.py:(1497) [ERROR]: Unhandled exception, please file a bug
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 1459, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 1541, in main
    return args.action(args, cfg=cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 146, in new_f
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 131, in new_f
    retval = f(*args, cfg=cfg, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 1065, in action_auto_attach
    actions.auto_attach(cfg, instance)
  File "/usr/lib/python3/dist-packages/uaclient/actions.py", line 51, in auto_attach
    tokenResponse = contract_client.request_auto_attach_contract_token(
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 128, in request_auto_attach_contract_token
    data=instance.identity_doc,
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 251, in decorator
    raise e
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 248, in decorator
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/clouds/gcp.py", line 33, in identity_doc
    url_response, _headers = util.readurl(
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 580, in readurl
    raise resp
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 560, in readurl
    resp = request.urlopen(req, timeout=timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
The unit also enters failed state due to this:

```
UNIT                   LOAD   ACTIVE SUB    DESCRIPTION                 
● ua-auto-attach.service loaded failed failed Ubuntu Advantage auto attach
```

The exception needs to be handled to suppress the `Unhandled exception, please file a bug` message, not sure what the unit state supposed to be.

**Comment by orndorffgrant** [comment]
Hi thank you for the bug report @ikapelyukhin! We haven't encountered this situation before and so we should probably handle it better.

It looks like `http://metadata/computeMetadata/v1/instance/service-accounts/default/identity?audience=contracts.canonical.com&format=full&licenses=TRUE` is returning 404, which is unusual.

Some questions that might help us reproduce this issue:
- What were the exact parameters with which you created this Pro GCP instance?
- Did this instance have a service account attached to it?

**Comment by ikapelyukhin** [comment]
>     * What were the exact parameters with which you created this Pro GCP instance?

This is from a pre-published Pro image in a testing pipeline. License hasn't been attached to the image yet.

>     * Did this instance have a service account attached to it?

No. That does seem to be the cause, here's the response body from an instance created via the same method:

```
$ curl -H 'Metadata-Flavor: Google' -v 'http://metadata/computeMetadata/v1/instance/service-accounts/default/identity?audience=contracts.canonical.com&format=full&licenses=TRUE'
*   Trying 169.254.169.254...
* Connected to metadata (169.254.169.254) port 80 (#0)
> GET /computeMetadata/v1/instance/service-accounts/default/identity?audience=contracts.canonical.com&format=full&licenses=TRUE HTTP/1.1
> Host: metadata
> User-Agent: curl/7.47.0
> Accept: */*
> Metadata-Flavor: Google
> 
< HTTP/1.1 404 Not Found
< Metadata-Flavor: Google
< Date: Thu, 20 Jan 2022 01:04:27 GMT
< Content-Type: text/html
< Server: Metadata Server for VM
< Content-Length: 94
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
< 
* Connection #0 to host metadata left intact
{"error":"invalid_request","error_description":"Service account not enabled on this instance"}
```

**Comment by orndorffgrant** [comment]
Thanks for the details!
Are you able to use enable a service account for your testing pipeline as a workaround for this issue?

We will also investigate if we can support instances without service-accounts.

**Comment by ikapelyukhin** [comment]
> Thanks for the details! Are you able to enable a service account for your testing pipeline as a workaround for this issue?

Yes.

> We will also investigate if we can support instances without service-accounts.

At the very least the exception should be handled. Displaying a nice error message and maybe directing to GCloud documentation on how to enable the service account would improve usability.

**Comment by orndorffgrant** [comment]
> At the very least the exception should be handled. Displaying a nice error message and maybe directing to GCloud documentation on how to enable the service account would improve usability.

Excellent point! We will do this at the very least

**Comment by orndorffgrant** [comment]
Tracking in SC-757
